### PR TITLE
Add '--validate-first' and '--ignore-outside' options to the flash command

### PR DESCRIPTION
**Pull request by N-Bz**
These options allow proper programming of atxmega devices with locked Application_Table sections (and probably other devices where a partial programming is done).

The `'--validate-first'` option avoid a check before calling the flash command, and will transform the flash command into a no-op if the embedded firmware is already the proper one.

The `'--ignore-outside'` option will tweak the `execute_validate(...)` function to return `SUCCESS` when `VALIDATION_ERROR_OUTSIDE_REGION` would have been returned without it.

The `atom.mk` file is here to allow building the program with [Alchemy](https://github.com/Parrot-Developers/alchemy), and should require no further maintenance (it only instructs alchemy to call the bootstrap.sh script and the build the program using the autotools.

Auto-completion and documentation are updated according to the changes.

### CODE REVIEW

**Comment by dwsobw** [comment]
Hi,

you use  "--verify-first" once in src/arguments.c but elsewhere you use "--validate-first". 
So the --help is will show the wrong one ..

cheers,
Daniel

**Comment by N-Bz** [comment]
Awww ... you're right !

I'll correct this.

**Comment by N-Bz** [comment]
Note:
I also removed the `atom.mk` file commit from this pull request, as it is not related to the new arguments.

**Comment by swinman** [comment]
It seems like the logic for doing the 'validate first' only happens if 'suppress validation' is also false.  I'm not sure they are related (except by name).  Validate first is really more of a 'check first to see if you really need to erase and re-program' whereas 'suppress validation' has to do with checking for success.  

i recommend removing line 507 in commands.c or returning an error for invalid flags when both validate-first and suppress validation are used.  Since it seems there are valid use cases for using both flags (speed), I think removing 507 is the better option.  

Do you mind removing that line and re-submitting.  Sorry for the delay

**Comment by rpavlik** [comment]
Any progress on this pull request? I of course can build it myself, but it would be really handy to have this feature (especially since it's not clear whether the erase command touches the bootloader or not on these xmegas we're using, so we're using the switch to not flash bootloader and aren't erasing first, so we get the validation failed outside anytime we flash with an image smaller than the largest thing we ICE'd)

**Pull request merged**
