### PR TITLE
Add basic coverage tests

### PR DESCRIPTION
**Pull request by cinderblock**
Basic test coverage instructions for my test rig.

I still need to add a workflow and trigger it somehow.

Or just bite the bullet and use a newer Pi that can run the GitHub Action Runner directly...

### CODE REVIEW

**Review by skirridsystems — DISMISSED** [review]

**Comment by cinderblock** [comment]
I've written this "framework" from scratch but I wonder if it would make more sense to leverage some other tool to "run" the tests (and generate a nice pretty report of what worked and what didn't). I've worked in the JavaScript world a lot and think we could use those tools to wrap and run the built binary in a variety of ways. Or maybe we should use a dedicated C/C++ unit testing framework?

In the end, I think it's most important that the outputs *look* good to humans and that developers can see the failing test results/criteria quickly and clearly.

**Comment by PhilippHaefele** [comment]
Hi cinderblock,
the [Robot Framework](https://robotframework.org) is maybe suitable for what you're planning to do and helps speeding up things.

Best regards

**Comment by cinderblock** [comment]
@PhilippHaefele neat project. I'm personally not a big Python user so I don't think this suits my particularities.

---

@skirridsystems I'm a fan of JavaScript (TypeScript) in the rest of my life. Any objection to a [Jest](https://jestjs.io) based tester?

---

I've just sent to fab a new HAT for a Pi to help make it easier to reproducibly make and run testers. I hope to find the time to get this running in the next week.

image

**Comment by skirridsystems** [comment]
No objection from me for using Jest.
Simon

**Comment by cinderblock** [comment]
@skirridsystems I took a first stab at getting a Jest tester working. I opted to keep the `package.json` at the top level, but could be convinced to put it inside `test`. What are your thoughts?

**Comment by skirridsystems** [comment]
@cinderblock I'll leave this up to you. Interested to learn about it, but it's way outside my area!

**Comment by cinderblock** [comment]
Well, the tests run and pass on my dev system, but are *far* from complete.

I'm hoping to get a Pi setup to run these tests over the weekend and the new test HAT should be in early next week. It should be quick to assemble and then we can test and publish some coverage results!

Then we can let people go to town writing more tests! I'm sure we won't get to *full* coverage, especially since this is just one piece of hardware, but it's a start and could be modified to run tests on other processors too!

**Comment by cinderblock** [comment]
@skirridsystems In case you didn't notice, I merged this branch.

Basic tests are working and it should be possible for others to recreate this platform to run the tests themselves.

Now is the hard work of adding more coverage tests to get this number up: [Coverage Status](https://coveralls.io/github/dfu-programmer/dfu-programmer)

**Pull request merged**
